name: Node.js CI

on: [push]

env:
  NEXT_PUBLIC_REACTFULLPAGE_LICENSE_KEY: ${{ vars.NEXT_PUBLIC_REACTFULLPAGE_LICENSE_KEY }}
  NEXT_PUBLIC_GOOGLE_ANALYTICS: ${{ vars.NEXT_PUBLIC_GOOGLE_ANALYTICS }}
  NEXT_PUBLIC_CONTACT_EMAIL: ${{ vars.NEXT_PUBLIC_CONTACT_EMAIL }}
  NEXT_PUBLIC_CONTACT_LINKEDIN: ${{ vars.NEXT_PUBLIC_CONTACT_LINKEDIN }}
  NEXT_PUBLIC_CONTACT_GITHUB: ${{ vars.NEXT_PUBLIC_CONTACT_GITHUB }}
  NEXT_PUBLIC_CONTACT_MEDIUM: ${{ vars.NEXT_PUBLIC_CONTACT_MEDIUM }}
  NEXT_PUBLIC_DOMAIN_EN: ${{ vars.NEXT_PUBLIC_DOMAIN_EN }}
  NEXT_PUBLIC_DOMAIN_FR: ${{ vars.NEXT_PUBLIC_DOMAIN_FR }}
  NEXT_PUBLIC_DOMAIN: ${{ vars.NEXT_PUBLIC_DOMAIN }}
  NEXT_PUBLIC_DOMAIN_PROTOCOL: ${{ vars.NEXT_PUBLIC_DOMAIN_PROTOCOL }}
  DEFAULT_LOCALE: ${{ vars.DEFAULT_LOCALE }}

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - run: npm run build --if-present
      env:
        CI: true
